# EduFin Small Data Analysis

In [22]:
import pandas as pd

In [3]:
# Load the datasets
base_path = "../datasets/edufin_small/"
loans = pd.read_csv(base_path + "loans.csv")
customers = pd.read_csv(base_path + "customers.csv")
institutions = pd.read_csv(base_path + "institutions.csv")
dim_state = pd.read_csv(base_path + "dim_state.csv")
dim_city = pd.read_csv(base_path + "dim_city.csv")

print(f"Loaded {len(loans)} loans, {len(customers)} customers, {len(institutions)} institutions.")

Loaded 5000 loans, 5000 customers, 5000 institutions.

Loans Data

---

In [11]:
print(loans.shape)

(5000, 12)

In [4]:
loans.head().T

,0,1,2,3,4
loan_id,1,2,3,4,5
customer_id,2440,2440,2440,4195,4195
institution_id,2954,4741,902,4724,244
loan_amount,190607.125,425798.375,318341.25,327505.75,641567.8125
loan_status,Defaulted,Active,Defaulted,Active,Active
interest_rate,11.39,14.44,11.65,10.19,11.69
loan_tenure_months,84,48,96,48,84
application_date,08-12-2021,01-01-2022,06-03-2023,20-12-2024,16-11-2023
disbursement_date,23-12-2021,11-01-2022,12-04-2023,31-01-2025,10-12-2023
maturity_date,16-11-2028,21-12-2025,01-03-2031,10-01-2029,03-11-2030
emi_amount,3302.540039,11728.73047,5112.870117,8336.240234,11219.62012
purpose_of_loan,Living Expenses,Course Fees + Living,Course Fees + Living,Course Fees + Living,Hostel Fees

In [5]:
loans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   loan_id             5000 non-null   int64
 1   customer_id         5000 non-null   int64
 2   institution_id      5000 non-null   int64
 3   loan_amount         5000 non-null   float64
 4   loan_status         5000 non-null   str
 5   interest_rate       5000 non-null   float64
 6   loan_tenure_months  5000 non-null   int64
 7   application_date    5000 non-null   str
 8   disbursement_date   5000 non-null   str
 9   maturity_date       5000 non-null   str
 10  emi_amount          5000 non-null   float64
 11  purpose_of_loan     5000 non-null   str
dtypes: float64(3), int64(4), str(5)
memory usage: 468.9 KB

In [6]:
loans.describe()

,loan_id,customer_id,institution_id,loan_amount,interest_rate,loan_tenure_months,emi_amount
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,2512.424800,2508.967800,409647.530216,12.774654,66.434400,9351.156296
std,1443.520003,1447.892317,1451.615069,179183.167676,1.931708,20.491815,4838.812471
min,1.000000,2.000000,1.000000,150000.000000,9.000000,36.000000,2209.429932
25%,1250.750000,1267.750000,1253.750000,281780.656300,11.377500,48.000000,5891.707397
50%,2500.500000,2483.500000,2506.500000,367388.546900,12.785000,72.000000,8153.925049
75%,3750.250000,3798.250000,3780.250000,488399.304700,14.110000,84.000000,11571.584957
max,5000.000000,5000.000000,5000.000000,986731.500000,17.000000,96.000000,32366.269530

Customers Data

---

In [12]:
print(customers.shape)

(5000, 13)

In [14]:
customers.head()

,customer_id,full_name,phone_number,email_address,city_id,current_address,annual_income,cibil_score,employemnet_type,employer_name,date_of_birth,gender,eduction_level
0,1,Dayita Bakshi,917486879361,dayita.bakshi680@yahoo.com,1002,"218, Sami Zila, Ludhiana 338908",1.156843e+06,832,Government Employee,Public Sector Bank,18-09-1995,Female,Bachelors
1,2,Hardik Saini,918893807924,hardik.saini599@yahoo.com,1010,40/26 Mall Path Thrissur-116155,3.103851e+05,672,Private Employee,Tech Solutions Ltd,16-07-1995,Male,Diploma
2,3,Libni Bassi,918288939172,libni.bassi694@hotmail.com,1027,"18, Pathak Road, Coimbatore-341316",1.925882e+06,668,Business Owner,Own Business,12-10-2003,Female,Bachelors
3,4,Liam Setty,917068528481,liam.setty637@hotmail.com,1027,"H.No. 53, Bora Road, Deoghar 276483",3.495068e+05,606,Self Employed,Self Employed,10-06-2003,Male,Bachelors
4,5,Omaja Bhalla,919789173738,omaja.bhalla245@outlook.com,1001,"H.No. 64, Kakar Zila Rajpur Sonarpur-672423",1.513292e+05,600,Student,Part-time Work,09-09-1996,Female,Bachelors

In [15]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   int64
 1   full_name         5000 non-null   str
 2   phone_number      5000 non-null   int64
 3   email_address     5000 non-null   str
 4   city_id           5000 non-null   int64
 5   current_address   5000 non-null   str
 6   annual_income     5000 non-null   float64
 7   cibil_score       5000 non-null   int64
 8   employemnet_type  5000 non-null   str
 9   employer_name     5000 non-null   str
 10  date_of_birth     5000 non-null   str
 11  gender            5000 non-null   str
 12  eduction_level    5000 non-null   str
dtypes: float64(1), int64(4), str(8)
memory usage: 507.9 KB

In [16]:
customers.describe()

       customer_id  phone_number      city_id  annual_income  cibil_score
count  5000.000000  5.000000e+03  5000.000000   5.000000e+03  5000.000000
mean   2500.500000  9.184971e+11  1015.351400   8.027324e+05   695.728400
std    1443.520003  8.657281e+08     8.733932   4.817649e+05    74.093467
min       1.000000  9.170003e+11  1001.000000   2.899421e+04   478.000000
25%    1250.750000  9.177622e+11  1008.000000   4.707362e+05   643.000000
50%    2500.500000  9.184942e+11  1015.000000   6.943262e+05   698.000000
75%    3750.250000  9.192389e+11  1023.000000   1.023079e+06   750.000000
max    5000.000000  9.199996e+11  1030.000000   3.816412e+06   884.000000

Institutions Data

---

In [17]:
print(institutions.shape)

(5000, 9)

In [19]:
institutions.head().T

,0,1,2,3,4
institution_id,1,2,3,4,5
institution_name,National Technology College,Central Law University,State Management University,Advanced Arts & Science College,Regional Law University
city_id,1025,1017,1024,1025,1030
institution_type,College,University,University,College,University
establishment_year,2007,1963,2009,1971,1987
total_students,4006,3919,4432,5607,2709
average_course_fee,53861.78906,313573.25,133544.2969,93312.1875,298089.5625
placement_rate,69.550003,63.25,58.27,48.25,83.349998
accreditation_status,NAAC A,NBA Accredited,NAAC B+,UGC Recognized,NBA Accredited

In [21]:
institutions.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   institution_id        5000 non-null   int64
 1   institution_name      5000 non-null   str
 2   city_id               5000 non-null   int64
 3   institution_type      5000 non-null   str
 4   establishment_year    5000 non-null   int64
 5   total_students        5000 non-null   int64
 6   average_course_fee    5000 non-null   float64
 7   placement_rate        4758 non-null   float64
 8   accreditation_status  5000 non-null   str
dtypes: float64(2), int64(4), str(3)
memory usage: 351.7 KB