# EduFin National Data Analysis

In [2]:
import pandas as pd

In [3]:
# Load the datasets
base_path = "../datasets/edufin_national/"
loans = pd.read_csv(base_path + "loans.csv")
customers = pd.read_csv(base_path + "customers.csv")
institutions = pd.read_csv(base_path + "institutions.csv")
dim_state = pd.read_csv(base_path + "dim_state.csv")
dim_city = pd.read_csv(base_path + "dim_city.csv")

print(f"Loaded {len(loans)} loans, {len(customers)} customers, {len(institutions)} institutions.")

Loaded 500000 loans, 100000 customers, 5000 institutions.

Loans Data

---

In [5]:
print(loans.shape)

(500000, 12)

In [4]:
loans.head().T

,0,1,2,3,4
loan_id,1,2,3,4,5
customer_id,67635,53320,96263,2964,99864
institution_id,47,28,43,35,4
loan_amount,257163.56,455070.21,230634.4,112423.27,215592.78
interest_rate,12.66,13.03,14.66,13.55,14.67
disbursement_date,2023-04-19,2022-08-31,2023-10-18,2024-03-16,2023-02-21
application_date,2023-03-13,2022-08-09,2023-08-31,2024-01-23,2023-01-27
maturity_date,2026-04-03,2025-08-15,2028-09-21,2029-02-18,2026-02-05
loan_status,Active,Active,Active,Active,Overdue
default_date,NaN,NaN,NaN,NaN,NaN
loan_purpose,Hostel,Living Expenses,Hostel,Equipment,Tuition
program_type,Domestic,Domestic,Domestic,Domestic,Domestic

In [6]:
loans.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   loan_id            500000 non-null  int64
 1   customer_id        500000 non-null  int64
 2   institution_id     500000 non-null  int64
 3   loan_amount        500000 non-null  float64
 4   interest_rate      500000 non-null  float64
 5   disbursement_date  500000 non-null  str
 6   application_date   500000 non-null  str
 7   maturity_date      500000 non-null  str
 8   loan_status        500000 non-null  str
 9   default_date       69290 non-null   str
 10  loan_purpose       500000 non-null  str
 11  program_type       500000 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 45.8 MB

In [8]:
loans.describe()

,loan_id,customer_id,institution_id,loan_amount,interest_rate
count,500000.000000,500000.000000,500000.000000,5.000000e+05,500000.000000
mean,250000.500000,50014.961254,25.459878,4.494587e+05,13.144422
std,144337.711635,28898.238162,14.423757,3.423418e+05,2.544554
min,1.000000,1.000000,1.000000,-3.591618e+05,8.500000
25%,125000.750000,24975.000000,13.000000,2.044543e+05,10.970000
50%,250000.500000,50049.000000,25.000000,3.262827e+05,13.110000
75%,375000.250000,75060.000000,38.000000,6.091872e+05,15.160000
max,500000.000000,100000.000000,50.000000,1.499999e+06,18.000000

Customers Data

---

In [9]:
print(customers.shape)

(100000, 12)

In [10]:
customers.head().T

,0,1,2,3,4
customer_id,1,2,3,4,5
full_name,Abhimanyu Pillai,Upasna Saini,Ekta Purohit,Gauri Rama,Zarna Kaur
gender,Male,Female,Female,Female,Female
age,27,21,19,24,28
city_id,26,4,2,40,19
annual_income,937495.03,751532.21,531462.53,304784.35,445698.18
income_bracket,High,Medium,Medium,Medium,Medium
cibil_score,743,535,647,512,611
employment_type,Salaried,Student,Student,Self-Employed,Salaried
customer_since,2025-03-07,2024-01-22,2023-12-27,2024-05-08,2024-01-06
status,Active,Active,Active,Active,Active
campaign_flag,NaN,NaN,NaN,NaN,NaN

In [11]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   customer_id      100000 non-null  int64
 1   full_name        100000 non-null  str
 2   gender           100000 non-null  str
 3   age              100000 non-null  int64
 4   city_id          100000 non-null  int64
 5   annual_income    100000 non-null  float64
 6   income_bracket   100000 non-null  str
 7   cibil_score      100000 non-null  int64
 8   employment_type  91710 non-null   str
 9   customer_since   100000 non-null  str
 10  status           100000 non-null  str
 11  campaign_flag    1033 non-null    str
dtypes: float64(1), int64(4), str(7)
memory usage: 9.2 MB

In [12]:
customers.describe()

,customer_id,age,city_id,annual_income,cibil_score
count,100000.000000,100000.000000,100000.000000,1.000000e+05,100000.000000
mean,50000.500000,24.710810,19.618560,6.267821e+05,585.473510
std,28867.657797,4.485383,13.090814,5.883206e+05,121.062016
min,1.000000,18.000000,1.000000,0.000000e+00,350.000000
25%,25000.750000,21.000000,9.000000,2.177418e+05,503.000000
50%,50000.500000,24.000000,17.000000,4.273380e+05,582.000000
75%,75000.250000,28.000000,31.000000,7.384197e+05,680.000000
max,100000.000000,35.000000,45.000000,2.499970e+06,999.000000

Institutions Data

---

In [13]:
print(institutions.shape)

(5000, 9)

In [14]:
institutions.head().T

,0,1,2,3,4
institution_id,1,2,3,4,5
institution_name,National Technology College,Central Law University,State Management University,Advanced Arts & Science College,Regional Law University
city_id,1025,1017,1024,1025,1030
institution_type,College,University,University,College,University
establishment_year,2007,1963,2009,1971,1987
total_students,4006,3919,4432,5607,2709
average_course_fee,53861.78906,313573.25,133544.2969,93312.1875,298089.5625
placement_rate,69.550003,63.25,58.27,48.25,83.349998
accreditation_status,NAAC A,NBA Accredited,NAAC B+,UGC Recognized,NBA Accredited

In [15]:
institutions.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   institution_id        5000 non-null   int64
 1   institution_name      5000 non-null   str
 2   city_id               5000 non-null   int64
 3   institution_type      5000 non-null   str
 4   establishment_year    5000 non-null   int64
 5   total_students        5000 non-null   int64
 6   average_course_fee    5000 non-null   float64
 7   placement_rate        4758 non-null   float64
 8   accreditation_status  5000 non-null   str
dtypes: float64(2), int64(4), str(3)
memory usage: 351.7 KB

In [16]:
institutions.describe()

,institution_id,city_id,establishment_year,total_students,average_course_fee,placement_rate
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,4758.000000
mean,2500.500000,1015.301200,1988.866800,8125.881200,287552.017593,67.929727
std,1443.520003,8.699794,17.704478,5979.888781,177958.716245,14.652824
min,1.000000,1001.000000,1950.000000,504.000000,50023.660160,35.029999
25%,1250.750000,1008.000000,1975.000000,3699.000000,158080.941425,58.132501
50%,2500.500000,1015.000000,1989.000000,6120.000000,236675.101600,69.000000
75%,3750.250000,1023.000000,2004.000000,10782.000000,363762.531250,79.457499
max,5000.000000,1030.000000,2020.000000,24991.000000,799935.250000,95.000000